"""Planner — the Manager's internal planning/reasoning engine.

Generates a structured ExecutionPlan before any agents are dispatched.
"""

from __future__ import annotations

import json
import logging
from dataclasses import asdict, dataclass, field
from typing import Any

from l90.blackboard.blackboard import Blackboard
from l90.models.provider import ModelProvider
from l90.tracing.logger import ReasoningTraceLogger

logger = logging.getLogger(__name__)

PLANNING_SYSTEM_PROMPT = """\
You are the Planning Engine of L90, a zero-hallucination scientific RAG system.

Your job is to analyze the user's query and produce a structured execution plan.

Given:
- The user's query
- The current operation mode
- The available collections

You MUST output a JSON object with exactly these fields:
{
  "mode": "<STRICT|PARTIAL|GENERAL|INCOGNITO|WORKSPACE>",
  "allowed_collections": ["collection_name_1", ...],
  "retrieval_strategy": "<single_pass|multi_pass|targeted>",
  "num_retrieval_agents": <1-5>,
  "requires_math_verification": <true|false>,
  "requires_physics_verification": <true|false>,
  "max_correction_loops": <0-3>,
  "reasoning": "<brief explanation of why this plan was chosen>"
}

Rules:
- In STRICT mode, only user_private_collection is allowed.
- In PARTIAL mode, user, workspace, and approved_library collections are allowed.
- In GENERAL mode, all collections are allowed, RAG is optional.
- In INCOGNITO mode, only incognito_session_collection and approved_library_collection.
- In WORKSPACE mode, workspace_collection and approved_library_collection.
- Use multi_pass for complex multi-step queries.
- Use targeted for queries about specific documents.
- Enable math/physics verification for technical queries.
- Set num_retrieval_agents higher for broad queries.
"""


@dataclass
class ExecutionPlan:
    """Structured execution plan generated by the PlannerLayer."""

    mode: str = "STRICT"
    allowed_collections: list[str] = field(default_factory=list)
    retrieval_strategy: str = "single_pass"
    num_retrieval_agents: int = 1
    requires_math_verification: bool = False
    requires_physics_verification: bool = False
    max_correction_loops: int = 3
    reasoning: str = ""

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


class PlannerLayer:
    """The Manager's planning engine — analyzes queries and produces ExecutionPlans.

    This is separate from the ManagerAgent because:
    1. Planning is a distinct cognitive step from orchestration
    2. The planner can be tested independently
    3. Different manager models may have different planning capabilities
    """

    def __init__(self, trace_logger: ReasoningTraceLogger | None = None) -> None:
        self._trace = trace_logger

    async def create_plan(
        self,
        blackboard: Blackboard,
    ) -> ExecutionPlan:
        """Analyze the query on the Blackboard and produce an ExecutionPlan.

        Uses the manager model to generate the plan as structured JSON.
        """
        model = ModelProvider.get_manager_model()

        prompt = (
            f"Query: {blackboard.query}\n"
            f"Current Mode: {blackboard.mode}\n"
            f"User ID: {blackboard.user_id}\n"
            f"Workspace ID: {blackboard.workspace_id}\n"
            f"Available Collections: {blackboard.allowed_sources}\n\n"
            "Generate the execution plan."
        )

        try:
            result = await model.generate_json(
                prompt=prompt,
                system_instruction=PLANNING_SYSTEM_PROMPT,
                temperature=0.0,
            )

            plan = ExecutionPlan(
                mode=result.get("mode", blackboard.mode),
                allowed_collections=result.get("allowed_collections", blackboard.allowed_sources),
                retrieval_strategy=result.get("retrieval_strategy", "single_pass"),
                num_retrieval_agents=result.get("num_retrieval_agents", 1),
                requires_math_verification=result.get("requires_math_verification", False),
                requires_physics_verification=result.get("requires_physics_verification", False),
                max_correction_loops=result.get("max_correction_loops", 3),
                reasoning=result.get("reasoning", ""),
            )

        except (ValueError, KeyError) as exc:
            logger.warning("Planning failed, using defaults: %s", exc)
            plan = ExecutionPlan(
                mode=blackboard.mode,
                allowed_collections=blackboard.allowed_sources,
                reasoning=f"Fallback plan — planning model error: {exc}",
            )

        # Record the plan in the trace
        if self._trace:
            self._trace.log(
                agent_name="PlannerLayer",
                phase="planning",
                action="create_execution_plan",
                input_summary=f"Query: {blackboard.query[:100]}",
                output_summary=f"Strategy: {plan.retrieval_strategy}, Agents: {plan.num_retrieval_agents}",
                decision=plan.reasoning,
            )

        # Write plan to Blackboard
        blackboard.execution_plan = plan.to_dict()
        blackboard.add_trace(
            agent_name="PlannerLayer",
            phase="planning",
            action="plan_created",
            details=plan.to_dict(),
        )

        return plan
